### ISSUE TITLE
Can't run correctly

### ISSUE THREAD

**Issue by IceKube987** [tianqiyuan520/TMinecraftFunctionMaker#1]
is this an incompleted project or what?

**Comment by tianqiyuan520** [comment]
there might be some bugs need fixing

**Comment by oinpig** [comment]
天起源太强了

________________________________
发件人: tianqiyuan520 ***@***.***>
发送时间: 2023年6月4日 16:29
收件人: tianqiyuan520/TMinecraftFunctionMaker ***@***.***>
抄送: oinpig ***@***.***>; Author ***@***.***>
主题: Re: [tianqiyuan520/TMinecraftFunctionMaker] Can't run correctly (Issue #1)


Closed #1<https://github.com/tianqiyuan520/TMinecraftFunctionMaker/issues/1> as completed.

―
